data<-read.csv.sql(file ="household_power_consumption.txt",sql= "select * from file where Date in ('1/2/2007','2/2/2007') ",sep =";")
librar(lubridate)
h<-paste(data$Date,data$Time)
g<-dmy_hms(h)
data<-mutate(data,datetime=g)
with(data,plot(datetime,Sub_metering_3+Sub_metering_2+Sub_metering_1,type= "n",xlab="",ylab="Energy sub metering"))
with(data,points(datetime,Sub_metering_3,col="blue",type ="s"))
with(data,points(datetime,Sub_metering_2,col="red",type ="s"))
with(data,points(datetime,Sub_metering_1,col="black",type ="s"))
legend("topright",col=c("blue","red","black"),legend = c("Sub_metering_3","Sub_metering_2","Sub_metering_1"),lty=1)