data<-read.csv.sql(file ="household_power_consumption.txt",sql= "select * from file where Date in ('1/2/2007','2/2/2007') ",sep =";")
librar(lubridate)
h<-paste(data$Date,data$Time)
g<-dmy_hms(h)
data<-mutate(data,datetime=g)
par(mfrow=c(2,2),mai=c(.5,.6806,.5,.6806))
with(data,plot(datetime,Global_active_power,type ="l",xlab = "",ylab ="Globalactivepower(killowatt)" ))
 with(data,plot(datetime,Voltage,type="l"))
 with(data,plot(datetime,Sub_metering_3+Sub_metering_2+Sub_metering_1,type= "n",xlab="",ylab="Energy sub metering"))
 with(data,points(datetime,Sub_metering_3,col="blue",type ="s"))
with(data,points(datetime,Sub_metering_2,col="red",type ="s"))
 with(data,points(datetime,Sub_metering_1,col="black",type ="s"))
 legend("topright",col=c("blue","red","black"),legend = c("Sub_metering_3","Sub_metering_2","Sub_metering_1"),lty=1,bty="n",cex = 0.7)
 with(data,plot(datetime,Global_reactive_power,type="l"))
dev.copy(png,file = "plot4.png")
dev.off()